
title:
  en: Phoenix site's site
  es: El sitio del sitio del fénix
email: phoenixsitegit@outlook.com
description:
  en: Carlos Romero Cruz, computer engineer and mathematician, passionate about Information and Machine Learning Security.
  es: Carlos Romero Cruz, ingeniero informático y matemático, apasionado de la seguridad en la información y en el aprendizaje automático.
baseurl: ""
url: https://phoenixsite.github.io

# Build settings
# theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
languages: ["es", "en"]
default_lang: "es"
parallel_localization: false

minima:
  date_formats:
    en: "%b. %e, %Y" # e.g.: Sep. 1, 2022
    es: "%d/%m/%y" # e.g.: 1/9/22
  social_links:
    - { icon: "github", titles: {en: Github profile, es: Perfil de Github}, url: "https://github.com/phoenixsite/" }
  feed_title:
    en: Subscribe to syndication feed
    es: Suscríbete al canal de difusión
  show_excerpts: true
  nav_pages:
    en:
      - projects-en.md
      - cv-en.md
    es:
      - projects-es.md
      - cv-es.md

sass:
  quiet_deps: true
  silence_deprecations: [import]

whitelist:
  - jekyll-redirect-from
